stages:
  train:
    cmd: python3 train.py
    deps:
      - train.py
    outs:
      - model.h5
    metrics:
      - metrics.yaml:
          cache: false
    live:
      metrics:
        cache: false
        summary: false
        html: false
